### ISSUE TITLE
Adding docker-compose support

### ISSUE THREAD

**Issue by apoclyps** [tulikavijay/CBT-therapy#11]
### Feature Request

As a developer that would like to contribute to this project, I would like to make greater use running the application in docker by adding a `docker-compose.yml` file to allow the application to be built and run with minimum setup by running the `docker-compose up --build` command after cloning the repository. 

Other benefits of including a `docker-compose.yml` file are that it allows for additional containers to also be created such as a database which could be used to replace SQLite. Heroku supports free hosting for databases making it feasible to change the database at a later time.

If this is something you would be happy to include, I can prepare a PR for you to review.

**Comment by tulikavijay** [comment]
I am not familiar with docker. But i think a commit related to docker has already been merged. For reference : #4
Do let me know if there's more that can be done.

**Comment by apoclyps** [comment]
The addition of docker-compose would make it easier for new developers to the project to build and run the application (assuming they have docker installed). 

I've added #17 for your consideration. I'd be happy to discuss this further if you have any questions or would like to pair on running it locally :)
