### ISSUE TITLE
Replace Python 2.7 with Python 3.7

### ISSUE THREAD

**Issue by apoclyps** [tulikavijay/CBT-therapy#12]
### Feature Request

Python 2.7 is no longer supported. I would like to upgrade this application to run on Python 3.7 to ensure it's long term maintainability. 

If you are happy with this change, I would like to upgrade the python version and migrate any code from 2.7 to 3.7

**Comment by tulikavijay** [comment]
Thankyou for submitting this. I recently updated the django version, it will be awesome if you can update the python version too.

**Comment by apoclyps** [comment]
Sure, I'll bump the python version via docker file, and the follow up that PR once I know it works in isolation with instructions on how to run it on a host machine.
