### ISSUE TITLE
wrong command in README.md file

### ISSUE THREAD

**Issue by perun-01** [tulikavijay/CBT-therapy#13]
![image](https://user-images.githubusercontent.com/43863911/67056861-8cf26000-f16b-11e9-9023-818ddf4b58e6.png)
wrong command: git checkout branch local-dev
correct command: git checkout local-dev

**Comment by tulikavijay** [comment]
Good catch! thanks for the PR.

**Comment by perun-01** [comment]
Do i have to create another PR for the same??
