### ISSUE TITLE
Add prompt for enabling GPS 

### ISSUE THREAD

**Issue by tulikavijay** [tulikavijay/CBT-therapy#2]
The webpage for showing nearest health center requires the GPS to be enabled. In the mobile and web configuration there should be a prompt for the user to enable GPS. The current functionality shows a blank webpage when GPS is not enabled.

**Comment by Abhinay1997** [comment]
Hello @tulikavijay I would like to work on this.

**Comment by tulikavijay** [comment]
Go for it!

**Comment by tulikavijay** [comment]
Closed #3
