### ISSUE TITLE
Improve the UI for CBT therapy page

### ISSUE THREAD

**Issue by tulikavijay** [tulikavijay/CBT-therapy#7]
#### Description: 
The text is too big. The button is too small. Choose a font that looks good.

#### Before Submitting PR:
Attach a Screenshot of your changes.

Link : https://nameless-island-79297.herokuapp.com/CBT_therapy/

**Comment by ghost** [comment]
Hi, can I work on this?

**Comment by tulikavijay** [comment]
Sure. Go ahead :)

**Comment by ghost** [comment]
Hi, @tulikavijay 

I saw in the base.html that there are two versions of bootstrap, 3.3.7 and 4.0.0-alpha.6. They might be affecting the CSS. Here you can find an example:

Example with the two CSS references:
![current-cbt](https://user-images.githubusercontent.com/37906201/67305560-22b72380-f4bb-11e9-9e6b-ec26dc81f9cd.png)

Example with just the 4.0.0-alpha.6:
![updated-cbt](https://user-images.githubusercontent.com/37906201/67305637-42e6e280-f4bb-11e9-86d7-032752692f81.png)

**Comment by tulikavijay** [comment]
Nice catch! if it doesn't affect other pages (please do check) then you can go ahead and remove that line and submit a PR. Also make sure that you make changes to the master branch or you can create a new branch that can merge with master.

**Comment by mridul-arora** [comment]
Hi, Can I work on this? I can fix the button & make it more aesthetically pleasing. Along with that your Nav Bar and your Registration page look odd.

**Comment by tulikavijay** [comment]
@mridul-arora Hi! thankyou for thinking of contributing to the project. UI can always be made better so you can go ahead and add your changes. I'll review once done.
